language: objective-c

before_script:
  - git clone git://github.com/jedisct1/libsodium.git
  - cd libsodium
  - git checkout tags/0.4.2
  - ./autogen.sh
  - ./configure && make check -j3
  - sudo make install
  - cd ..
  - git submodule init
  - git submodule update
  - cd DeepEnd
  - git submodule init
  - git submodule update
  - cd ..

script: xcodebuild -workspace Poison.xcworkspace -scheme Poison

notifications:
  email:
    recipients:
      - "stal+builds@pyboard.net"
    on_success: always
    on_failure: always

  irc:
    channels:
      - "chat.freenode.net#tox-dev"
    on_success: always
    on_failure: always
